-- Run this script in your Supabase SQL Editor to initialize the database schema

DROP TABLE IF EXISTS grading_systems CASCADE;
DROP TABLE IF EXISTS fees CASCADE;
DROP TABLE IF EXISTS borrowing CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS marks CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;
DROP TABLE IF EXISTS schools CASCADE;

CREATE TABLE schools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'active', -- 'active', 'suspended'
  address TEXT,
  phone TEXT,
  email TEXT,
  motto TEXT
);

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT,
  role TEXT NOT NULL, -- 'super_admin', 'associate_admin', 'school_head', 'teacher', 'student', 'librarian', 'accounts_clerk'
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  admission_number TEXT,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

CREATE TABLE classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

CREATE TABLE enrollments (
  student_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  PRIMARY KEY (student_id, class_id),
  FOREIGN KEY (student_id) REFERENCES app_users(id) ON DELETE CASCADE,
  FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  score REAL NOT NULL,
  term TEXT NOT NULL,
  year INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (student_id) REFERENCES app_users(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  FOREIGN KEY (teacher_id) REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE TABLE materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  type TEXT NOT NULL, -- 'exam', 'note', 'marking_scheme'
  content TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'approved'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
  FOREIGN KEY (teacher_id) REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE TABLE books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  status TEXT DEFAULT 'available', -- 'available', 'borrowed'
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

CREATE TABLE borrowing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  borrow_date TIMESTAMPTZ DEFAULT NOW(),
  return_date TIMESTAMPTZ,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE TABLE fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  amount REAL NOT NULL,
  paid REAL DEFAULT 0,
  balance REAL NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (student_id) REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE TABLE grading_systems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL,
  min_score REAL NOT NULL,
  max_score REAL NOT NULL,
  grade TEXT NOT NULL,
  points INTEGER NOT NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);
